name             'cookbook'
maintainer       'Me'
maintainer_email 'me@there.com'
license          'All rights reserved'
description      'Installs/Configures cookbook'
long_description 'Installs/Configures cookbook'
version          '0.1.0'
